# Generated by Django 5.1.3 on 2024-11-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_id', models.IntegerField()),
                ('join_date', models.DateField()),
                ('result', models.CharField(max_length=50)),
            ],
        ),
    ]
